proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80" # bind ports 80 and 443 directly to the host
    - "443:443"
  volumes:
    - ./volumes/etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /ssl/certs:/etc/nginx/certs
  environment:
    DEFAULT_HOST: 112.74.107.49
